### ISSUE TITLE
ModuleNotFoundError: No module named 'models.experimental'

### ISSUE THREAD

**Issue by sard0r** [abanitalebi/simrod#1]
Hello

Dear SimROD authors it was very enjoyful to read your paper. As soon as I read your paper I was rushing to implement and found the code.

But while executing the code I came across to a problem ModuleNotFoundError: No module named 'models.experimental'.
![Screenshot from 2021-11-08 15-26-23](https://user-images.githubusercontent.com/61651742/140694147-b42badf2-6e01-40b0-a3d2-da1c4aba3043.png)

I hope this issue will be solved. Thank you!

**Comment by abanitalebi** [comment]
Hi Sardor. 
Thanks for your interest in our work.

Please carefully double check to ensure you are following the exact same procedure that is described here:
https://marketplace.huaweicloud.com/markets/aihub/notebook/detail/?id=d6d7162f-32b9-483d-97d7-b16b32b148e2

Also, please make sure to use the same package versions (e.g. PyTorch etc.).

After that, if versions and environment are identical to the above notebook, take a look at this issue to see if yours is a similar problem: https://github.com/ultralytics/yolov5/issues/353

If not, please open an issue here: 
https://github.com/reactivetype/simrod/issues

**Comment by sard0r** [comment]
Thank you for your quick reply!

First of all I did everything I could. I checked the requirements more than 10 times and run the code in my machine and colab but the same issue  is raising and raising again.

I also raised issue https://github.com/reactivetype/simrod/issues.

But Dr.Rindra Ramamonjison did not respond to the issue. Can you please help to solve the issue if possible?

**Comment by sard0r** [comment]
New issue after correcting others.

![Screenshot from 2021-11-10 13-47-41](https://user-images.githubusercontent.com/61651742/141052431-74888c4a-58a3-402c-826b-9296a909aaa8.png)


Please help!

**Comment by abanitalebi** [comment]
Both this issue and the previous one sound like issues with paths. 
Things I would suggest is to ensure setting the correct PYTHONPATH environment variable (especially if you are not using an IDE), or try executing the code from the code root directory may resolve this issue.

**Comment by abanitalebi** [comment]
Also, I noticed that your python is 3.8, but the one we used is 3.7 I believe (double check with the notebook). This may or may not be the cause of these issues, but I should point out the code wasn't tested with 3.8.

**Comment by sard0r** [comment]
I think while running this code you guys encountered this problem and solved it especially Dr.Rindra. But he is opting not to answer. Is not it good if public uses your code and your work will be famous all over the world like YOLO models. But I don't know I tried to change everything Cuda path and etc. It would be really helpful if you guys make a tutorial how to run the code. 

Thanks

**Comment by sard0r** [comment]
Thanks I solved the issue

**Comment by Eggyyyy** [comment]
@sard0r Hi sard0r,
I met the issue you had before.
![image](https://user-images.githubusercontent.com/90384203/141430029-44745445-1ac4-4431-a60b-a7a9ee9b885e.png)
Could you please share your solution to this issue?
Thanks!
