### ISSUE TITLE
guild: cannot find operation comic:adapt

### ISSUE THREAD

**Issue by Eggyyyy** [abanitalebi/simrod#3]
Dear SimROD authors,
I'm following the https://marketplace.huaweicloud.com/markets/aihub/notebook/detail/?id=d6d7162f-32b9-483d-97d7-b16b32b148e2, and my **guild check** is shown below：
![image](https://user-images.githubusercontent.com/90384203/141307728-4be34801-08c2-4484-8188-290f1c70a267.png)
When I start adapting the teacher model, running the command 'guild run comic:adapt warmup_epochs=2 finetune_epochs=3 cfg=models/yolov5x.yaml .......', there is no operation **comic:adapt**.
In fact, my guild doesn't have any operation! But I have pip the guild, I think there must be some problem about my install for guild!

**Comment by abanitalebi** [comment]
Or maybe it's not finding some necessary data/config/yaml files? Guild state seems okay..
If you have all the config/data/yaml files in place, then maybe it's about setting the correct PYTHONPATH or executing the code from the right root dir so it can actually see those files.

One way to narrow down the issue, is to run in the notebook itself, and see if it can run. If it runs in the browser (which should be the case), then run in your local environment cell-by-cell and compare the logs/outputs.

**Comment by Eggyyyy** [comment]
Hi abanitalebi,
Thanks for your reply! 
I have solved this problem, it's really a code path problem. Thanks a lot!
