### ISSUE TITLE
Pseudolabeling 

### ISSUE THREAD

**Issue by sard0r** [abanitalebi/simrod#4]
Hello  Dr.Amin,

I solved many issues that I encountered but I cannot figure out which pretrained weight it is using to generate the first pseudo labeling.
in that case I am running comic:adapt

Also, when I run coco_c:adapt it is showing me cannot find source file 'data/voc_cat-contrast-3.yaml' issue. 

It would be helpful if you make a tutorial because your model is the best suit to generate pseudo labels saving lots of time.

Thanks 

Sardor

**Comment by sard0r** [comment]
@abanitalebi 
Dr.Amin
If you change the code in yolo.py 130 line b[:, 4] += math.log(8 / (640 / s) ** 2) # obj (8 objects per 640 image) and next line to  
b[:, 4].data += math.log(8 / (640 / s) ** 2)  # obj (8 objects per 640 image)
b[:, 5:].data += math.log(0.6 / (m.nc - 0.99)) if cf is None else torch.log(cf / cf.sum())  # cls

your code can be run Pytorch agnostic. 
Thnak you

**Comment by abanitalebi** [comment]
Good find @sard0r

**Comment by sard0r** [comment]
@abanitalebi 

Thank you sir! I want to ask help from you. As your code can only be run on yolov5 archive I couldnot use my custom weights to generate pseudolabels. When I added everything from yolov5 there is a problem in adapt.py and label.py.

Traceback (most recent call last):
  File "/home/bae/.guild/runs/f3877d85c7b04320a40552e803be3160/.guild/sourcecode/adapt.py", line 266, in <module>
    adapt(data_dict, opt)
  File "/home/bae/.guild/runs/f3877d85c7b04320a40552e803be3160/.guild/sourcecode/adapt.py", line 65, in adapt
    labeler.generate_labels(step_1_source, step_1_weights, opt, step_1_labels_dir, step_1_predictions_dir, opt.label_img_size)
  File "/home/bae/.guild/runs/f3877d85c7b04320a40552e803be3160/.guild/sourcecode/label.py", line 72, in generate_labels
    for path, img, im0s, vid_cap in tqdm(dataset):
ValueError: too many values to unpack (expected 4)

this is the latest error. I deleted apex from adapt.py because I could not run after that it popped out.

thank you beforehand.

**Comment by sard0r** [comment]
It would be great if you guys update your code to the latest yolov5 codes and make simple tutorial. 

I hope you will find. @abanitalebi

**Comment by abanitalebi** [comment]
Hi @sard0r 
Unfortunately we don't have enough bandwidth to spend on syncing the code with newer updates of the Yolo repo; sorry for that.

That being said, it should technically not be difficult to bring back the changes from there, as we don't touch the Yolo architecture. We do have a notebook here: https://developer.huaweicloud.com/develop/aigallery/notebook/detail?id=d6d7162f-32b9-483d-97d7-b16b32b148e2

Hope it can be useful.
